"""Reusable structural-family catalog for experimental N4 discovery.

The catalog describes the **pre-graph provider inputs** required by each family.
Internal graph-support columns are generated by :mod:`acsp.structural_graph` and
are deliberately not user/provider requirements. These are development contracts,
not occupancy models.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class StructuralFamilySpec:
    family_id: str
    label: str
    ecological_question: str
    required_raw_columns: tuple[str, ...]
    source_roles: tuple[str, ...]
    notes: str


STRUCTURAL_FAMILIES: dict[str, StructuralFamilySpec] = {
    "WETLAND_MOISTURE_STRUCTURE": StructuralFamilySpec(
        family_id="WETLAND_MOISTURE_STRUCTURE",
        label="Wetland / moisture continuity",
        ecological_question="Does a moist or wetland-associated structural component continue through the candidate frame?",
        required_raw_columns=(
            "wc_water_frac_250m",
            "wc_wetland_frac_250m",
            "slope100",
            "tpi300",
        ),
        source_roles=("landcover", "terrain"),
        notes="WorldCover-style water/wetland fractions and terrain are provider inputs; terrain continuity is built internally on the frozen grid graph.",
    ),
    "ALPINE_TOPOGRAPHIC_STRUCTURE": StructuralFamilySpec(
        family_id="ALPINE_TOPOGRAPHIC_STRUCTURE",
        label="Alpine topographic continuity",
        ecological_question="Does the same high-relief landform component continue beyond known populations?",
        required_raw_columns=("elev", "slope100", "tpi300", "rough300"),
        source_roles=("terrain",),
        notes="Relative elevation and landform/ridge-valley continuity are derived outcome-blind from the declared terrain grid.",
    ),
    "OPEN_GRASSLAND_STRUCTURE": StructuralFamilySpec(
        family_id="OPEN_GRASSLAND_STRUCTURE",
        label="Open grassland / fragment continuity",
        ecological_question="Are open grassland fragments structurally connected or repeated across the justified frame?",
        required_raw_columns=("wc_grass_frac_250m", "slope100", "tpi300", "rough300"),
        source_roles=("landcover", "terrain"),
        notes="Open-land fraction and terrain are provider inputs; fragment continuity is generated internally rather than fitted from outcomes.",
    ),
    "COASTAL_ISLAND_STRUCTURE": StructuralFamilySpec(
        family_id="COASTAL_ISLAND_STRUCTURE",
        label="Coastal / island structure",
        ecological_question="Does a shore-position and island-component structure justify looking beyond known coastal populations?",
        required_raw_columns=(
            "coast_distance_m",
            "wc_grass_frac_250m",
            "wc_bare_frac_250m",
            "ecological_component_id",
        ),
        source_roles=("coastline", "landcover", "component_geometry"),
        notes="Coast distance, shore cover and a predeclared ecological component are inputs; shore continuity is generated internally. target_component_id must also be declared.",
    ),
    "FOREST_EDGE_STRUCTURE": StructuralFamilySpec(
        family_id="FOREST_EDGE_STRUCTURE",
        label="Forest-edge structure",
        ecological_question="Do canopy transitions and terrain components repeat along forest edges?",
        required_raw_columns=(
            "wc_tree_frac_250m",
            "wc_edge_mix_250m",
            "slope100",
            "tpi300",
            "rough300",
        ),
        source_roles=("landcover", "terrain"),
        notes="Tree fraction, edge mixing and terrain are inputs; terrain-component continuity is generated internally.",
    ),
}


def list_structural_families() -> tuple[StructuralFamilySpec, ...]:
    """Return all currently frozen development families in stable order."""
    return tuple(STRUCTURAL_FAMILIES[key] for key in sorted(STRUCTURAL_FAMILIES))


def get_structural_family_spec(family_id: str) -> StructuralFamilySpec:
    key = str(family_id).strip()
    try:
        return STRUCTURAL_FAMILIES[key]
    except KeyError as exc:
        raise ValueError(
            f"unknown structural family {key!r}; available: {', '.join(sorted(STRUCTURAL_FAMILIES))}"
        ) from exc
