"""Reusable ACSP survey-planning methods."""

from .field_calibration import (
    DEFAULT_FIELD_FEATURE_SPECS,
    DEFAULT_FIELD_RADIUS_WEIGHTS,
    RankConfiguration,
    add_within_area_rank_features,
    apply_rank_configuration,
    attach_field_utility,
    calibrate_field_ranker,
    enumerate_rank_configurations,
    recovery_metrics as field_calibration_recovery_metrics,
    select_one_per_area,
)
from .field_validation import (
    DEFAULT_RECOVERY_RADII_KM,
    cluster_field_detections,
    detection_recovery_table,
    haversine_distance_m,
    normalize_field_locations,
    recovery_summary,
    stratified_random_recovery_benchmark,
)
from .planning import (
    DEFAULT_INTEGRATED_WEIGHTS,
    aggregate_candidates_to_zones,
    compare_zone_rankings,
    filter_candidates_to_extent,
    integrated_candidate_scores,
    normalize_extent,
    recommend_candidates,
    recommend_survey_zones,
    select_complementary_candidates,
    zone_agreement_summary,
)
from .modeling import DEFAULT_ENSEMBLE_ALGORITHMS, make_classifier, predict_equal_weight_ensemble
from .sdm import choose_spatial_partition, model_performance_table, sdm_method_record
from .validation import (
    calibrate_candidate_weights,
    clustered_recovery_inference,
    calibrate_model_ensemble_weights,
    multi_taxon_weight_benchmark,
    spatial_block_candidate_benchmark,
    spatial_block_recovery_validation,
    spatial_model_accuracy_benchmark,
    stratified_random_taxa,
)

__all__ = [
    "choose_spatial_partition",
    "DEFAULT_INTEGRATED_WEIGHTS",
    "DEFAULT_ENSEMBLE_ALGORITHMS",
    "DEFAULT_RECOVERY_RADII_KM",
    "DEFAULT_FIELD_FEATURE_SPECS",
    "DEFAULT_FIELD_RADIUS_WEIGHTS",
    "RankConfiguration",
    "attach_field_utility",
    "add_within_area_rank_features",
    "enumerate_rank_configurations",
    "apply_rank_configuration",
    "select_one_per_area",
    "calibrate_field_ranker",
    "field_calibration_recovery_metrics",
    "make_classifier",
    "model_performance_table",
    "filter_candidates_to_extent",
    "integrated_candidate_scores",
    "aggregate_candidates_to_zones",
    "compare_zone_rankings",
    "normalize_extent",
    "recommend_candidates",
    "recommend_survey_zones",
    "select_complementary_candidates",
    "predict_equal_weight_ensemble",
    "sdm_method_record",
    "calibrate_candidate_weights",
    "clustered_recovery_inference",
    "calibrate_model_ensemble_weights",
    "multi_taxon_weight_benchmark",
    "spatial_block_candidate_benchmark",
    "spatial_block_recovery_validation",
    "spatial_model_accuracy_benchmark",
    "stratified_random_taxa",
    "zone_agreement_summary",
    "haversine_distance_m",
    "normalize_field_locations",
    "cluster_field_detections",
    "detection_recovery_table",
    "recovery_summary",
    "stratified_random_recovery_benchmark",
]

__version__ = "0.1.0"
